### ISSUE TITLE
[M0] ¿Qué es un suministro?

### ISSUE THREAD

**Issue by DarckMonster** [danieeeld2/LogisticsRoutes#11]
Cuando tenemos que repartir un suministro, en #5 tenemos que tener en cuenta las características del mismo. 

¿Cuál será el dominio de las características de un suministro?

Una vez tengamos definidas las características de un suministro podremos saber como será la entidad suministro.

**Comment by danieeeld2** [comment]
En [HU.md](https://github.com/danieeeld2/LogisticsRoutes/blob/main/docs/historias.md) estan especificados los tipos de suministros en un comentario. Que lo añadí después de la práctica pero no lo añadí en el issue estrictamente, perdona.

**Comment by DarckMonster** [comment]
Perfecto, pues con esto podemos empezar a definir le entidad suministro en el nuevo issue #13.
