### ISSUE TITLE
[M0] ¿Cómo será la clase camión?

### ISSUE THREAD

**Issue by DarckMonster** [danieeeld2/LogisticsRoutes#12]
Para crear el objeto de valor camión tenemos que saber como va a ser.
¿Son todos los suministros aptos para todos los camiones?
¿Que características pueden diferenciar a los camiones?

**Comment by danieeeld2** [comment]
Al haber suministros que requieran una cámara frigorífica o que sean productos químicos, bastaría con tener camiones "normales" camiones "frigoríficos" y camiones "químicos"

**Comment by DarckMonster** [comment]
Bien @danieeeld2 la entidad camión tendrá los siguientes atributos si te parece bien:

Clase `Camión` o `Camion` o `Truck`
* `tipo` o `type` que sería un struct entre `normal`, 'frigorífico' y 'químico'.
* `altura` o `heigth` en cuanto a dimensiones lo importante al circular es la altura del vehículo por la posible imposibilidad de circular por determinadas vías, por puentes por ejemplo.

Si crees que hace falta modificar o añadir algun atributo esperearé tus recomendaciones.

**Comment by danieeeld2** [comment]
Yo añadiría también un atributo de carga máxima que soporta el vehículo o capacidad. Existen algunas leyes legislativas que regulan el peso máximo que pueden soportar los mismos, para que sea seguro circular.

**Comment by DarckMonster** [comment]
Si, es cierto. La MMA (masa máxima autorizada) es una característica muy importante a la hora de llevar mercancía.

Clase `Camion` 
* `tipo` que sería un struct entre `normal`, `frigorífico` y `químico`.
* `altura`  en cuanto a dimensiones lo importante al circular es la altura del vehículo por la posible imposibilidad de circular por determinadas vías, por puentes por ejemplo.
* `mma` masa máxima autorizada, característica importante de cada camión

**Comment by danieeeld2** [comment]
Yo aquí creo que como no vamos a trabajar directamente con rutas, sino que vamos a hacer un problema de asignación y optimización, la altura no es un dato relevante, pero si lo puede ser la capacidad, para ver si las dimensiones del suministro entran en el camión o si se necesitan varios. ¿No sé como lo ves?

**Comment by DarckMonster** [comment]
La verdad lo veo con más sentido. La capacidad en cuanto a volumen también es muy importante. La clase quedaría así: 

Clase `Camion` 
* `tipo` que sería un struct entre `normal`, `frigorífico` y `químico`.
* `capacidad`  altura, profundidad, anchura
* `mma` masa máxima autorizada
