### ISSUE TITLE
[M0] ¿Clase suministro?

### ISSUE THREAD

**Issue by DarckMonster** [danieeeld2/LogisticsRoutes#13]
Vamos a ver como será el objeto de valor suministro dadas las restricciones que se nos pide en la HU #5. Pondremos estos atributos:
* Peso
* Dimensiones
* Tipo (Frío, químico, indiferente)

Dime que te parece o si quieres hacer algún cambio :blush:.

**Comment by danieeeld2** [comment]
Los suministros, así de primeras, tiene pinta que van a ser un objeto-valor, por lo que necesitan ser identificados sin necesidad de IDs y van a ser objetos inmutables. Yo añadiría la dirección a donde hay que enviarlos (también puedes añadir quien los solicita) y puede ser apropiado añadir la distancia a la que está el punto de entrega para refinar el problema de planificación

**Comment by danieeeld2** [comment]
De todas formas tu plantea todo según las HUs y lo que creas conveniente, justificando algunas decisiones a través de los issues, que te van a permitir dividir el problema en sub-problemas más simples hasta llegar a que lo que tienes que programar es un objeto-valor o una entidad. Ya una vez este todo yo reviso y puedo aportar alguna sugerencia, pero en principio la práctica es para que, a través de la documentación, tu llegues a un PMV. Confio en que lo harás bien compañero 😄. 

Por cierto, por lo que he entendido en clase e investigando un poco proyectos de otros años, para pasar la práctica lo mejor es que los issue aporten valor y que hagan referencia a alguna HU u otro issue; por si te sirve de ayuda este comentario para plantearlo jeje. Si necesitas que haga algo (asociar algún issue al M0, poner una etiqueta a un issue...) etiquetame, que me salta automáticamente en la app del móvil y lo hago tan pronto como sea posible.

Mucho animo con la práctica compañero💪

**Comment by DarckMonster** [comment]
> Los suministros, así de primeras, tiene pinta que van a ser un objeto-valor, por lo que necesitan ser identificados sin necesidad de IDs y van a ser objetos inmutables. Yo añadiría la dirección a donde hay que enviarlos (también puedes añadir quien los solicita) y puede ser apropiado añadir la distancia a la que está el punto de entrega para refinar el problema de planificación

Entiendo lo que quieres decir, haremos de suministro una entidad que alberga tanto las características de la entrega como la propia entrega. Entonces sus atributos serían los siguietes.

* `Dirección de entrega`
* `Tiempo de entrega` En lugar de indicar la distancia creo que es más conveniente utilizar el tiempo que se tarda en llegar al destino.
* `Peso`
* `Dimensiones`
*  `Tipo` (Refrigerado, químico, normal)

Ya me vas comentando @danieeeld2 :smiley:

**Comment by danieeeld2** [comment]
Me parece correcto lo de usar un tiempo estimado de entrega, nos ahorramos el problema de trabajar con las distancias. 😄

**Comment by DarckMonster** [comment]
Con esto último, un suministro pasa a ser un objeto valor.

**Comment by JJ** [comment]
Un issue plantea un problema, no una solución. "Pondremos" no parece que plantee ningún problema. Por lo menos con la discusión parece que el issue ha ido por el buen camino, pero a priori deberías repensar cómo planteas los issues.

**Comment by danieeeld2** [comment]
> Un issue plantea un problema, no una solución. "Pondremos" no parece que plantee ningún problema. Por lo menos con la discusión parece que el issue ha ido por el buen camino, pero a priori deberías repensar cómo planteas los issues.

Si quieres JJ me pongo con Juan este finde o comienzos de semana a ayudar a plantearlos mejor, ya que yo pasé el objetivo. Yo creo que lo mejor va a ser marcar estos con una etiqueta de `invalid` y desarrollarlos de nuevo fijándose en las discusiones que hemos tenido a través de estos.

**Comment by DarckMonster** [comment]
> > Un issue plantea un problema, no una solución. "Pondremos" no parece que plantee ningún problema. Por lo menos con la discusión parece que el issue ha ido por el buen camino, pero a priori deberías repensar cómo planteas los issues.
> 
> Si quieres JJ me pongo con Juan este finde o comienzos de semana a ayudar a plantearlos mejor, ya que yo pasé el objetivo. Yo creo que lo mejor va a ser marcar estos con una etiqueta de `invalid` y desarrollarlos de nuevo fijándose en las discusiones que hemos tenido a través de estos.

Si, es mejor hacer eso 👍 .
