### ISSUE TITLE
[M0] Propuesta de estructura de de datos y ficheros

### ISSUE THREAD

**Issue by DarckMonster** [danieeeld2/LogisticsRoutes#14]
Como estamos en el M0 nos centramos en la HU1 #5  que trata de la asignación de camiones con restricciones como residuos que no pueden ir en cualquier camión. Como ya hemos discutido sobre los distintos objetos, tendremos una entidad y un objeto valor.

* `Suministro` entidad que controla tanto la mercancía como el reparto. #13 
* `Camion` que tendrá la información del camión al que se le ha asignado un suministro. #12 

Por tanto tendremos dos ficheros: `suministro.go` y `camion.go` que tendrán cada una su clase correspondiente.

En cuanto tenga el visto bueno puedo empezar a crear los ficheros.

**Comment by danieeeld2** [comment]
Creo que hace también falta una entidad que refleje la planificación. El M0 es la base para resolver todo lo siguiente y nuestro objetivo en M2 es hacer una planificación, por lo que necesitaremos una estructura que vaya recogiendo las asignaciones suministro-camión de forma ordenada.

**Comment by DarckMonster** [comment]
Entonces creamos otra entidad Planificador que recoja las asignaciones de los suministros a los camiones y además servirá para futuros milestones. 

* `Suministro` entidad que controla tanto la mercancía como el reparto. #13 
* `Camion` que tendrá la información del camión al que se le ha asignado un suministro. #12 
* `Planificacion` entidad para guardar las asignaciones suministro-camión.

**Comment by DarckMonster** [comment]
Ya deben de estar terminadas las clases. He hecho una modificación en `camion.go` para que cada objeto Camion tenga un array de Suministros y despues en `Planificacion.go` tenemos el array de camiones.
