### ISSUE TITLE
[M0] Atributos de la clase de planificacion.go

### ISSUE THREAD

**Issue by DarckMonster** [danieeeld2/LogisticsRoutes#20]
Haciendo caso a los comentarios, he pensado como cambiar esta clase.

He pensado en tener así Planificacion:
* `camiones` array de los camiones
* `suministros` array de suministros
* `asignacion` map de `camiones` y  array de suministros: map[`camiones`][]Suministro

Así podremos tener el conjunto de camiones y suministros en una clase y su asignación. 

Tambien había pensado en hacer asignaciones así `[][]Suministro` y utilizar la posición del camión como identificador de la primera coordenada. Esto no sería correcto al tener que aclararlo, en contra del desarrollo ágil.

Si te parece bien lo paso al código @danieeeld2 .

**Comment by danieeeld2** [comment]
Me parece correcto, es un poco lo que había pensado yo. Otra opción que tienes de hacerlo es crearte una clase que sea `asignación` , que tenga como parámetro un suministro y un array de camiones (porque hay que tener en cuenta que si un suministro es muy grande puede necesitar más de un camión para ser entregado porque no "quepa" en el mismo). Y, después, en planificación, simplemente sea u array de estas asignaciones en orden de entrega.

**Comment by danieeeld2** [comment]
> Me parece correcto, es un poco lo que había pensado yo. Otra opción que tienes de hacerlo es crearte una clase que sea `asignación` , que tenga como parámetro un suministro y un array de camiones (porque hay que tener en cuenta que si un suministro es muy grande puede necesitar más de un camión para ser entregado porque no "quepa" en el mismo). Y, después, en planificación, simplemente sea u array de estas asignaciones en orden de entrega.

Mientras esté bien justificado no tengo problema en como lo hagas. Simplemente ten en cuenta que un suministro puede necesitar más de un camión para ser entregado. 😉

**Comment by DarckMonster** [comment]
Vale, entiendo lo que dices. Dado a que no encuentro esa restricción en las HU dejaré como está lo que he planteado. Además si se puede hacer lo que has comentado con la estructura propuesta como djiste :+1:.

**Comment by DarckMonster** [comment]
Además modificaré el resto de structs para hacer el código coherente.

**Comment by danieeeld2** [comment]
> Vale, entiendo lo que dices. Dado a que no encuentro esa restricción en las HU dejaré como está lo que he planteado. Además si se puede hacer lo que has comentado con la estructura propuesta como djiste 👍.

Perdona, creí que si lo había reflejado pero con tanto lío lo habré borrado en algún momento. Como no viene reflejado, si quieres quédate con lo que venga en los HU.😄
