### ISSUE TITLE
[M0] ¿Cómo representamos un suministro en Go y que unidades utilizamos? ¿Struct para diferenciar los tipos de suministro?

### ISSUE THREAD

**Issue by DarckMonster** [danieeeld2/LogisticsRoutes#22]
Hemos visto en #21 las características de un suministro y vamos a ver como construimos el struct de Golang para representar `Suministro`. Voy a poner las dimensiones en cm porque los paquetes no suelen superar varios metros, más bien no llegar a superar el metro de longitud. El peso en kg por ser la magnitud más adecuada. Y finalmente el tipo será un struct que albergue los tres tipos de suministros para poder hacer el enum en golang.

Propongo por tanto la siguiente solución atendiendo a lo hablado:

Suministro:
* `dimensiones_cm` vector de 3 float
* `peso_kg` float
* `tipo` tipoSuministro

El enum se trata de `normal`, `frigorifico`, `quimico`.

**Comment by danieeeld2** [comment]
Yo le pondría un título más representativo al issue ya que se parece mucho al #21. "Para la lógica de negocio necesitamos saber las unidades de medida de los atributos y como representar los tipos de camión" es el que se me ocurre a mi, puedes poner otro si quieres. Lo puedes cambiar desde el botón verde de edit arriba a la derecha. Lo digo porque se parecen muchos los dos que has creado, para que quede más claro.

**Comment by danieeeld2** [comment]
Por lo demás creo que ahora los estás planteando mucho mejor que antes. Sigue así compañero y ánimo😄

**Comment by danieeeld2** [comment]
había un error tipográfico, lo acabo de ajustar

**Comment by DarckMonster** [comment]
Pues no vi el cambio y sí había un error 😆
