### ISSUE TITLE
¿Con qué lenguaje de programación queremos trabajar?

### ISSUE THREAD

**Issue by DarckMonster** [danieeeld2/LogisticsRoutes#7]
Para saber que lenguaje de programación será el más adecuado tendremos que hacernos dos preguntas:
* ¿Qué lenguaje de programación es el más adecuado para el proyecto?
* ¿Es el lenguaje de programación cómodo para los desarrolladores?

Vamos a ver que lenguaje se adecúa más al proyecto.

**Comment by danieeeld2** [comment]
Buenas @DarckMonster, un placer trabajar contigo. Yo había estado pensando en hacerlo en lenguaje Go, porque además de las ventajas que tiene (como su sintaxis simple, excelente rendimiento y simple importación de dependencias), es un lenguaje del que no tengo mucho dominio y me gustaría aprovechar esta ocasión para aprender más sobre él. De todas formas me gustaría saber también tu opinión y si tienes alguna sugerencia 😄

**Comment by DarckMonster** [comment]
Buenas @danieeeld2, veo que tienes muchas ganas de usar `Go`, ganas que me has contagiado. No tengo experiencia en este lenguaje, pero estoy encantado de aprenderlo. Así que doy el visto bueno para utilizar este lenguaje de programación.

**Comment by danieeeld2** [comment]
Perfecto compañero :+1:
