### ISSUE TITLE
[M0] ¿Cuál es la magnitud del problema?

### ISSUE THREAD

**Issue by DarckMonster** [danieeeld2/LogisticsRoutes#9]
Para entender mejor el problema tenemos que ver cuál será la magnitud del problema, es decir, ¿estará reducida solo a una ciudad o son zonas más amplias?

Esto se debe a que los factores que tenemos que tener en cuenta son distintos si hay que hacer trayectos largos por autovía o solo hay que hacer rutas intraurbanas.

Para esto, tenemos que saber cual es el tamaño de las zonas que se controlan en las HHUU #5 #2 #3 #4.

**Comment by danieeeld2** [comment]
Yo creo que tampoco es tan relevante. Los objetivos que voy a trabajar en la asignatura es la asignación del camión/camiones más óptimo para un suministro y después la planificación primando el número de entregas. Se podría gestionar simplemente considerando el "tiempo estimado de entrega" o "distancia de reparto" y así no tienes en cuenta la ubicación geográfica estrictamente, sino una referencia. Si tienes alguna sugerencia te leo por aquí 😁

**Comment by DarckMonster** [comment]
Entiendo, entonces ya está más claro el problema. Además creo que respondes a #10 también, aunque te inivitaría a que me concretases en el propio issue.
